name: AlpineLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [3.9.3, 3.10.9, 3.11.11, 3.12.7, 3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      - run: apk add git

      - uses: actions/checkout@v2

      - run: |
          ls -a .
          cp -r . ..
          ls -a ..
