name: CentOS Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['7.5.1804', '8.3.2011']

    container: centos:${{ matrix.tag }}

    steps:
      - run: yum -y update && yum -y install git
        if:  ${{ matrix.tag == '7.5.1804' }}

      - run: dnf -y update && dnf -y install git
        if:  ${{ matrix.tag == '8.3.2011' }}

      - uses: actions/checkout@v2

      - run: |
          ls -a .
          cp -r . ..
          ls -a ..
