name: Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest

    defaults:
      run:
        shell: cygwin {0}

    steps:
    - run: choco install -y cygwin
      shell: pwsh

    - run: C:\tools\cygwin\bin\bash.exe --login -i -c "sed -i 's/--login -i/--login -i %1/' /cygdrive/c/tools/cygwin/Cygwin.bat"
      shell: pwsh
   
    - run: choco install -y --source cygwin git
    
    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v2
    
    - run: |
        cd '${{ github.workspace }}'
        ls -a .
        cp -r . ..
        ls -a ..
