name: run units target on MSYS2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        msystem: [MINGW32, MINGW64, CLANG32, CLANG64]

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: automake autoconf make dos2unix
        pacboy: toolchain:p python3-sphinx:p jansson:p libyaml:p pcre2:p

    - name: install libxml2-2.11.5
      run: |
        curl -LO https://download.gnome.org/sources/libxml2/2.11/libxml2-2.11.5.tar.xz
        tar vxf libxml2-2.11.5.tar.xz
        cd libxml2-2.11.5
        ./configure --prefix=/usr
        make
        make install

    - run: git config --global core.autocrlf input
      shell: bash

    - uses: actions/checkout@v4
      with:
        repository: universal-ctags/ctags

    - run: ./autogen.sh
    - run: ./configure --prefix=/usr
    - run: make V=1
    - run: make install
    - run: file /usr/bin/ctags
    - run: ctags --version

    - run: make check V=1

    # FAILED: "./readtags.exe" -t "/d/a/ctags2/ctags2/Units/parser-asciidoc.r/utf8-asciidoc.d/expected.tags" - "@–Ä‚ÄìêÄÄ"
    # The raw tag name was "@–Ä‚ÄìêÄÄ"
    #- run: make roundtrip

    - run: make tmain
    - run: make units
